
server:
  port: 8080
  servlet:
    context-path: /springboot-jedis

spring:
  redis:
    port: 6379
    host: 127.0.0.1
    password:
    timeout: 1800000
    database: 1
    jedis:
      pool:
        min-idle: 0
        max-idle: 100
        max-active: 100
        max-wait: -1



example:
  redis:
    scan:
      count: 300

