spring:
  redis:
    port: 6379
    host: 127.0.0.1
    password:
    timeout: 3000
    database: 1
    jedis:
      pool:
        min-idle: 2
        max-idle: 8
        max-active: 8
        max-wait: -1

example:
  redis:
    scan:
      count: 300