arthas:
  # telnetPort、httpPort为 -1 ，则不listen telnet端口，为 0 ，则随机telnet端口
  telnetPort: -1
  httpPort: -1
  # 127.0.0.1，本地访问，0.0.0.0，网络访问
  ip: 127.0.0.1
  appName: arthas_test
  # 默认情况下，会生成随机ID，如果 arthas agent配置了 appName，则生成的agentId会带上appName的前缀。
  agent-id: e9a2d4f3b8c7
  # tunnel-server地址
  tunnel-server: ws://127.0.0.1:7777/ws