spring:
  rabbitmq:
    host: 127.0.0.1      # RabbitMQ服务器的主机名或IP地址
    port: 5672                # RabbitMQ服务器的端口号（默认是5672）
    username: admin           # 连接RabbitMQ的用户名
    password: admin           # 连接RabbitMQ的密码
    virtual-host: /           # 使用的虚拟主机（默认是根目录/）
    listener:
      simple:
        acknowledge-mode: auto  # 消息确认模式：自动确认（消息被消费后自动确认）
        concurrency: 1          # 最小并发消费者数量
        max-concurrency: 1      # 最大并发消费者数量
        retry:
          enabled: true         # 启用消费失败重试机制
          max-attempts: 3       # 最大重试次数
          initial-interval: 3000ms  # 首次重试间隔时间（3秒）
  datasource:
    url: jdbc:mysql://127.0.0.1:3316/test?useSSL=false&serverTimezone=UTC
    username: your-username
    password: your-password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

# 日志配置
logging:
  level:
    root: INFO
    com.example: DEBUG