spring:
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    database: 0
  datasource:
    dynamic:
      primary: shop #设置默认的数据源或者数据源组,默认值即为master
      strict: false #严格匹配数据源,默认false. true未匹配到指定数据源时抛异常,false使用默认数据源
      datasource:
        shop:
          url: jdbc:mysql://127.0.0.1:3306/shop?useUnicode=true&characterEncoding=utf-8
          username: root
          password:
          driver-class-name: com.mysql.cj.jdbc.Drive# 3.2.0开始支持SPI可省略此配置
          schema: classpath:db/schema-mysql.sql
          data: classpath:db/data-mysql.sql
        slave_1:
          url: jdbc:mysql://127.0.0.1:3306/canaltest?useUnicode=true&characterEncoding=utf-8
          username: root
          password:
          driver-class-name: com.mysql.cj.jdbc.Drive

mybatis-plus:
  type-aliases-package: com.example.redis.*.*.model
  mapper-locations: classpath*:mapper/*/*.xml
  global-config:
    db-config:
      logic-not-delete-value: 1
      logic-delete-value: 0
  configuration:
    map-underscore-to-camel-case: true
    default-statement-timeout: 60
    cache-enabled: true
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl

